export const GETHOMELIST = "gethomelist" 
export const GETPOLICYLIST = "getpolicylist" 
export const GETCATEGORYLIST = "getCategorylist" 
export const GETCATEGORY = "getCategory" 
export const GETNAVLIST = "getNavList" 